version: "3.8"

services:
  sonarqube:
    image: sonarqube:latest
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=123
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    depends_on:
      - db

    networks:
      - sonar_network   
      - nova

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=sonar
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sonar_network   

volumes:
  sonarqube_data:
  db_data:

networks:
  sonar_network:
  nova:
    external: true